meta:
  url: https://hiroppy.github.io/fusuma-sample/
  name: Introduction slide of Fusuma
  author: Yuta Hiroto
  description: Introduce Fusuma
  thumbnail: https://avatars0.githubusercontent.com/u/3367801?s=400&v=4
  siteName: slides.hiroppy.me
  sns:
    - twitter
    - hatena
slide:
  theme: nebula
extends:
  css: style.css