meta:
  url: https://slides.hiroppy.me
  name: a sample for fusuma
  author: Yuta Hiroto
  description: Sample 
  thumbnail: https://avatars0.githubusercontent.com/u/3367801?s=400&v=4
  siteName: slides.hiroppy.me
slide:
  theme: js
extends:
  js:
  css: style.css
